Replace systemd-run calls with ssh
- Add bash library to be included inside other scripts
- Add nscd-cmd wrapper to execute commands inside the containter
- Add dropbear server inside the container
- Add dropbear client inside the host

diff --git a/root/usr/bin/nsdc-cmd b/root/usr/bin/nsdc-cmd
--- a/root/usr/bin/nsdc-cmd
+++ b/root/usr/bin/nsdc-cmd
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 #
-# Copyright (C) 2016 Nethesis S.r.l.
+# Copyright (C) 2018 Nethesis S.r.l.
 # http://www.nethesis.it - nethserver@nethesis.it
 #
 # This script is part of NethServer.
@@ -20,24 +20,39 @@
 # along with NethServer.  If not, see COPYING.
 #
 
-set -e -o pipefail
+# Execute a command inside the containter
 
-nsroot=/var/lib/machines/nsdc
+. /usr/share/nethserver-dc/nsdc-functions
 
-function cleanup ()
+function help
 {
-    rm -rf ${nsroot}
+    echo "Usage: $0 [-r] <cmd> [<args1> ... <argsN>]"
+    echo "  -r : execute raw command - use it for reading from stdin"
     exit 1
 }
 
-if [[ ! -x ${nsroot}/usr/sbin/samba ]]; then
-    trap cleanup ERR
-    mkdir -p ${nsroot}/etc/yum/vars
-    mkdir -p ${nsroot}/var/log/journal
-    mkdir -p ${nsroot}/etc/systemd/network
-    cp -f /etc/yum/vars/* ${nsroot}/etc/yum/vars
-    rpm --root=${nsroot} --import /etc/pki/rpm-gpg/*
-    yum -y --releasever=/ --installroot=${nsroot} install /usr/lib/nethserver-dc/ns-samba-*.ns7.x86_64.rpm centos-release systemd-networkd bind-utils ntp dropbear | /usr/libexec/nethserver/ptrack-nsdc-install
-    rm -f ${nsroot}/etc/krb5.conf
-    systemctl enable machines.target
+raw=0
+while getopts ":h:r" opt; do
+  case $opt in
+    h)
+      help
+      ;;
+    r)
+      raw=1
+      shift
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      ;;
+  esac
+done
+
+if [ $# -eq 0 ]; then
+    help
+fi
+
+if [ $raw -eq 1 ]; then
+    cmd_raw $@
+else
+    cmd $@
 fi
