Fix home dirs migration

diff --git a/root/etc/e-smith/events/actions/nethserver-dc-migrate b/root/etc/e-smith/events/actions/nethserver-dc-migrate
--- a/root/etc/e-smith/events/actions/nethserver-dc-migrate
+++ b/root/etc/e-smith/events/actions/nethserver-dc-migrate
@@ -20,8 +20,8 @@
 # along with NethServer.  If not, see COPYING.
 #
 
-event=$1
-sourceDir=$2
+event=${1:?missing event argument}
+sourceDir=${2:?missing sourceDir argument}
 destDir=/var/lib/machines/nsdc
 errors=0
 realm=$(/sbin/e-smith/config getprop sssd Realm)
@@ -150,6 +150,37 @@ EOF
 
 /etc/e-smith/events/actions/nethserver-dc-join ${event} || (( errors ++ ))
 /etc/e-smith/events/actions/nethserver-dc-user-lock ${event} administrator@${domain} || (( errors ++ ))
+
+# Migrate user home directories
+for sourceHomeDir in $sourceDir/home/e-smith/files/users/*; do
+
+    if [[ ! -d "$sourceHomeDir" ]]; then
+        continue
+    fi
+
+    userName=$(basename $sourceHomeDir)
+
+    if  ! getent passwd $userName >/dev/null ; then
+        echo "[ERROR] Could not find $userName in Unix user DB"
+        (( errors ++ ))
+        continue
+    fi
+
+    homeDir=$(eval echo "~$userName")
+
+    perl -MNethServer::Migrate -f - "$sourceHomeDir" "$homeDir" <<'EOF'
+mkdir $ARGV[1];
+chmod 0700, $ARGV[1];
+if(NethServer::Migrate::migrateDir($ARGV[0], $ARGV[1])) {
+    warn("[NOTICE] Migrated home directory $homeDir\n");
+} else {
+    warn("[ERROR] Could not migrate home directory $homeDir\n");
+    exit(1);
+}
+EOF
+
+    chown -R "$userName:domain users" $homeDir || (( errors ++ ))
+done
 
 if (( errors > 0 )); then
     exit 1
