Get exit status from user-lock/user-unlock output

diff --git a/root/etc/e-smith/events/actions/nethserver-dc-user-lock b/root/etc/e-smith/events/actions/nethserver-dc-user-lock
--- a/root/etc/e-smith/events/actions/nethserver-dc-user-lock
+++ b/root/etc/e-smith/events/actions/nethserver-dc-user-lock
@@ -1,8 +1,8 @@
-#!/usr/bin/perl -w
+#!/bin/bash
 
 #
 # Copyright (C) 2016 Nethesis S.r.l.
-# http://www.nethesis.it - nethserver@nethesis.it
+# http://www.nethesis.it - support@nethesis.it
 #
 # This script is part of NethServer.
 #
@@ -17,43 +17,28 @@
 # GNU General Public License for more details.
 #
 # You should have received a copy of the GNU General Public License
-# along with NethServer.  If not, see COPYING.
+# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
 #
 
-use strict;
-use esmith::db;
-use esmith::ConfigDB;
-use Errno;
-use English;
+if ! [ $# -ge 2 ]; then
+   echo "[ERROR] Not enough arguments."
+   exit 2
+fi
 
-my $event = shift;
-my $userName = shift;
+EVENT=$1
+USER=$2
+DOMAIN=$(hostname -d)
 
-if( ! $userName ) {
-    warn("[ERROR] Missing username argument");
-    exit(1);
+if ! [[ $USER == *"@${DOMAIN}" ]]; then
+    echo "[NOTICE] Skipping user ${USER}, it doesn't belong to our domain."
+    exit 0
+fi
+
+exec expect -f - <<EOF
+spawn -noecho /usr/bin/systemd-run -M nsdc -q -t /usr/bin/samba-tool user disable "${USER%@${DOMAIN}}"
+expect {
+    "ERROR" {exit 1}
+    eof {exit 0}
 }
-
-my $db = esmith::ConfigDB->open_ro() || die("Could not open Config DB");
-my $passwd = esmith::db->open("NethServer::Database::Passwd") || die("Could not open Passwd DB");
-
-
-# Handle users with and without domain part
-my $account = undef;
-if ($userName =~ /@/) {
-    $account = $passwd->get($userName);
-    $userName = (split(/@/,$userName))[0];
-} else {
-    my $domain = $db->get_value('DomainName');
-    $account = $passwd->get($userName.'@'.$domain);
-}
-if( ! $account) {
-    die "[ERROR] Account `$userName` not found.\n";
-}
-
-my $cmd = "/usr/bin/systemd-run -M nsdc -q -t /usr/bin/samba-tool user disable '$userName'" ;
-
-system($cmd) == 0
-        or die "[ERROR] running samba-tool command to lock account $userName";
-
-
+exit 2
+EOF
